"""Initial

Revision ID: 39712e0162a8
Revises: 
Create Date: 2025-03-14 06:53:04.573361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39712e0162a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_appointments', sa.Integer(), nullable=False),
    sa.Column('booked_appointments', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=49), nullable=False),
    sa.Column('password', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('username', sa.String(length=49), nullable=False),
    sa.ForeignKeyConstraint(['date'], ['appointments.date'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_appointments')
    op.drop_table('users')
    op.drop_table('appointments')
    # ### end Alembic commands ###
